from ETLTools.portfolio import Portfolio

if __name__ == "__main__":
    trade_history = [
        {
            "datetime": "2020-04-21 14:41:30",
            "exchange": "NSE",
            "segment": "EQ",
            "symbol": "TATAMOTORS",
            "scrip_name": "TATAMOTORS",
            "side": "BUY",
            "amount": "1051.4",
            "quantity": "14.0",
            "price": "75.1",
            "expiry_date": "nan",
        },
        {
            "datetime": "2020-05-04 14:33:45",
            "exchange": "NSE",
            "segment": "EQ",
            "symbol": "TATAMOTORS",
            "scrip_name": "TATAMOTORS",
            "side": "BUY",
            "amount": "419.0",
            "quantity": "5.0",
            "price": "83.8",
            "expiry_date": "nan",
        },
        {
            "datetime": "2020-05-05 11:31:20",
            "exchange": "NSE",
            "segment": "EQ",
            "symbol": "BHAGERIA",
            "scrip_name": "BHAGERIA",
            "side": "BUY",
            "amount": "1165.5",
            "quantity": "10.0",
            "price": "116.55",
            "expiry_date": "nan",
        },
        {
            "datetime": "2020-05-19 14:44:06",
            "exchange": "NSE",
            "segment": "EQ",
            "symbol": "BHAGERIA",
            "scrip_name": "BHAGERIA",
            "side": "BUY",
            "amount": "500.0",
            "quantity": "5.0",
            "price": "100.0",
            "expiry_date": "nan",
        },
        {
            "datetime": "2020-06-15 10:57:42",
            "exchange": "NSE",
            "segment": "EQ",
            "symbol": "BHAGERIA",
            "scrip_name": "BHAGERIA",
            "side": "SELL",
            "amount": "1695.0",
            "quantity": "15.0",
            "price": "113.0",
            "expiry_date": "nan",
        },
        {
            "datetime": "2020-07-03 13:31:19",
            "exchange": "NSE",
            "segment": "EQ",
            "symbol": "TATAMOTORS",
            "scrip_name": "TATAMOTORS",
            "side": "BUY",
            "amount": "1560.0",
            "quantity": "15.0",
            "price": "104.0",
            "expiry_date": "nan",
        },
        {
            "datetime": "2020-07-27 10:47:51",
            "exchange": "NSE",
            "segment": "EQ",
            "symbol": "YESBANK",
            "scrip_name": "YESBANK",
            "side": "BUY",
            "amount": "1230.0",
            "quantity": "100.0",
            "price": "12.3",
            "expiry_date": "nan",
        },
        {
            "datetime": "2020-07-29 14:11:01",
            "exchange": "NSE",
            "segment": "EQ",
            "symbol": "YESBANK",
            "scrip_name": "YESBANK",
            "side": "BUY",
            "amount": "587.5",
            "quantity": "50.0",
            "price": "11.75",
            "expiry_date": "nan",
        },
        {
            "datetime": "2020-07-29 14:12:52",
            "exchange": "NSE",
            "segment": "EQ",
            "symbol": "PNB",
            "scrip_name": "PNB",
            "side": "BUY",
            "amount": "988.5",
            "quantity": "30.0",
            "price": "32.95",
            "expiry_date": "nan",
        },
        {
            "datetime": "2020-07-29 14:14:01",
            "exchange": "NSE",
            "segment": "EQ",
            "symbol": "IDEA",
            "scrip_name": "IDEA",
            "side": "BUY",
            "amount": "164.0",
            "quantity": "20.0",
            "price": "8.2",
            "expiry_date": "nan",
        },
    ]

    portfolio = Portfolio()
    for record in trade_history:
        portfolio.trade(record)

    portfolio.check_expired_stocks()

    print(portfolio.get_pnl()[0])

    print(portfolio.get_holdings()[0])
