name: Run pre-commit

on:
  workflow_dispatch:
  push:
    branches:
      - 'main'
      - 'releases/**'

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@latest
      - uses: actions/setup-python@latest
      - uses: pre-commit/action@latest
      - run: |
          # Note: the following account information will not work on GHES
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "Fixed Code Quality"
          git push
