name: Pre-Commit Auto-Update

on:
  schedule:
    - cron: "0 0 1 * *" # midnight every first of the month

jobs:
  auto-update:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
      - uses: browniebroke/pre-commit-autoupdate-action@main
      - uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: update/pre-commit-hooks
          base: dev
          title: "Chore: Update Pre-Commit Hooks"
          commit-message: "chore: update pre-commit hooks"
          body: Update versions of pre-commit hooks to latest version.
