name: Run pre-commit

on:
  workflow_dispatch:
  push:
    branches:
      - 'main'
      - 'releases/**'

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@latest
      - uses: actions/setup-python@latest
      - uses: pre-commit/action@latest
